version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=seu_user
      - DB_PASSWORD=Sua_senha
      - DB_NAME=user_gerenciamento
      - JWT_SECRET=sua_jwt_secret
      - JWT_EXPIRES_IN=24h
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha
      MYSQL_DATABASE: user_gerenciamento
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: